### ISSUE TITLE
Plugin breaking admin access entirely?

### ISSUE THREAD

**Issue by gilliganondata** [ManageWP/broken-link-checker#32]
We've been using this plugin for a while, and it has worked great. We're not aware of any updates to our WP implementation (but are checking with our host to see if there were any updates they've made behind the scenes).

This morning, went we go to the /wp-admin URL for our site, we get the following error:

**Parse error:** syntax error, unexpected '[' in **/home/analytics/public_html/wp-content/plugins/broken-link-checker/core/core.php** on line **109**.

We can't even get into the admin area to disable the plugin.

Is this a plugin issue and, if not, any idea what the underlying issue is likely to be?

The site itself -- the public-facing content -- does not appear to be impacted by this.

**Comment by Zrgisa** [comment]
The latest update on the plugin repository should fix this. Please make sure you're using the latest version.

If that doesn't fix the problem, please contact me to fix this issue.
